version: '3'

services:
  vivia:
    build: .
    container_name: vivia
    network_mode: host
    ports:
      - 5000:5000
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN={DISCORD_TOKEN}